name: Publish Private Node.js Package

on:
  release:
    types: [created]

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 13
          registry-url: https://npm.pkg.github.com/
          scope: '@flight-squad'
        
      - name: Publish
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          npm ci
          npm run build
          npm config set //npm.pkg.github.com/:_authToken=$NODE_AUTH_TOKEN
          npm publish
