name: Publish Private Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 13
      - run: npm ci
      # - run: npm test

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 13
          registry-url: https://npm.pkg.github.com/
          scope: '@flight-squad'
      - run: npm ci
      - run: npm config set //npm.pkg.github.com/:_authToken=$NODE_AUTH_TOKEN && npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}